### ISSUE TITLE
Allow creating source map with node-sass

### ISSUE THREAD

**Issue by Sander-Toonen** [gremo/assetic-extra#1]
With the current filter there is no way to ask node-sass to generate a source map. Source maps are helpful during debugging of the css. I will soon add a PR for this issue.

**Comment by gremo** [comment]
Thank you, waiting for your PR 👍

**Comment by gremo** [comment]
So, If I set `source_map: true` in the configuration, what happens? A source map is created where, exactly?

**Comment by Sander-Toonen** [comment]
Yeah.. I'm still fighting with that... The only option I see for now is embedding the source map in de actual css. I might have been a bit too optimistic about implementing this feature in a usable way. Stay tuned :)

**Comment by Sander-Toonen** [comment]
Awesome!
